name: Main
on:
  push:
    branches: [ main ]
    
env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs:
  ubuntu-ci:
    name: Spectral CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v3
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --ok --engine-kinds packages --include-tags base,iac
